# Site settings
title: Hebi's Wiki
email: lihebi.com@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hebi's Online Knowledge Book, named Hebi's Wiki
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lihebi.com" # the base hostname & protocol for your site
twitter_username: lihebi
github_username:  lihebi

# Build settings
# markdown: kramdown

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# highlighter: pygments

# collections
collections:
  wiki:
    output: true
    permalink: /posts/:path/index.html

defaults:
  -
    scope:
      path: ""
      type: "wiki"
    values:
      layout: "page"
      title: No Title
